### ISSUE TITLE
ERROR: the path supplied to --osm-file does not exist

### ISSUE THREAD

**Issue by vipyoung** [twain47/Nominatim#110] opened 2014-02-04 09:05 UTC
Hi all, 
I have experienced a very annoying error while trying to install Nominatim on Ubuntu 13.10 server with ext4 file system.
The error comes right after I run the command: ./utils/setup.php --osm-file planet-latest.osm.pbf 
Here is the error I got: 
ERROR: the path supplied to --osm-file does not exist

After some investigations, it turned out that setup.php is calling /lib/cmd.php which uses realpath() php function. 
However, as per PHP documentation, realpath may return unexpected results for files which are larger than 2GB on some filesystem [http://php.net/realpath].

The solution would be to modify /lib/cmd.php script by removing the call to realpath. 
i.e.,
case 'realpath':
// comment this one
// $xVal[] = realpath($aArg[$i]);
// add this line
$xVal[] = $aArg[$i];

Once you are done with this modification, make sure you provide the exact path to you osm.pbf file in the above command.

**Comment by lonvia** [comment] 2015-01-30 19:58
Closing because it cannot be reproduced. Please reopen, if you can tie this to a specific OS/PHP version

**Closed by lonvia** 2015-01-30 19:58 UTC
