### ISSUE TITLE
Strange error, on details.php

### ISSUE THREAD

**Issue by soulraven** [twain47/Nominatim#233] opened 2015-02-06 08:08 UTC
i get this error, in the secound that i have created a new nominatim server,
http://nominatim.2.acronshop.ro/details.php?place_id=31643326
Notice: Undefined index: place:neighbourhood in /opt/Nominatim/website/details.php on line 79

i have found that inside the getClassTypes() from lib.php is missing the place:neighbourhood key from the array. What is the value for this element?

**Comment by lonvia** [comment] 2015-02-06 08:37
The fact that it is missing is not a problem by itself, although we really should be checking for it to avoid the warning. Normally, this notice should go into the log file not to stdout. Check your php configuration.

**Comment by soulraven** [comment] 2015-02-06 09:17
the log setting is now in stdout, to check for possibile problems, for case like this.

**Comment by lonvia** [comment] 2015-08-08 16:20
I cannot reproduce the warning. Could you please provide an example using an object from the current API?

**Comment by lonvia** [comment] 2016-01-22 22:56
Closing because of missing details.

**Closed by lonvia** 2016-01-22 22:56 UTC
Labels: API, bug
