### ISSUE TITLE
Create db on remote host

### ISSUE THREAD

**Issue by winsento** [twain47/Nominatim#423] opened 2016-04-05 16:56 UTC
How i can create database and load data if postgres run on remote host.  

`./utils/setup.php --create-db` submit only port and database name like this `createdb -E UTF-8 -p 5432 nominatim`.

**Comment by mtmail** [comment] 2016-04-06 18:35
Hi Andrew,

Part of the installation is building/compiling a `nominatim.so` shared library which the Postgres server needs to be able to access locally. So using a remote Postgres server isn't always possible. Now if you use Docker you might be able to copy the file or build the file on the Postgres server (I haven't tried that). If the remote Postgres server is a hosted solution like Amazon RDS you won't be able to do that.

**Comment by winsento** [comment] 2016-04-23 17:30
@mtmail  thank you for your answer. Im wrote a Dockerfile for Nominatim here  https://github.com/cartography/nominatim-docker and it works well. But it is bad practice to run multiple services in a single container.
I want to divide Postgres and Nominatim into two separate containers.

1. I can write Dokerfile for Postgres with `nominatim.so`, building and compile with Nominatim and remove sources after that.
2. But i can't create database and load data if Postgres run on remote host.

My experement in `refactoring` branch here https://github.com/cartography/nominatim-docker/blob/refactoring/Dockerfile

**Comment by lonvia** [comment] 2016-04-24 13:10
As a work-around, you can create the DB separately and then skip the create-db step by calling setup like this:

    ./utils/setup.php --setup-db --import-data --create-functions --create-tables --create-partition-tables --create-partition-functions --import-wikipedia-articles --load-data --calculate-postcodes --osmosis-init --index --create-search-indices --osm-fle <yourfile>

A pull request that gets rid of the remaining locations where nominatim makes assumptions about the location of the DB instead of using CONST_Database_DSN would also be welcome.

You probably also need to hack the location of nominatim.so. If you like to make a pull request that makes the location configurable via settings.local.php instead of using the fixed `CONST_InstallPath.'/module'` path, then we can include that as well in the official code.

**Comment by lonvia** [comment] 2016-04-24 20:59
Actually a duplicate of #318.

**Closed by lonvia** 2016-04-24 20:59 UTC
Labels: duplicate
