### ISSUE TITLE
Case-sensivity in query with starting lower case letter "г"

### ISSUE THREAD

**Issue by 0x836** [twain47/Nominatim#398] opened 2016-03-16 04:21 UTC
This bug https://trac.openstreetmap.org/ticket/2758#comment:6 is still reprodused.

**Comment by mtmail** [comment] 2016-03-16 12:30
Thanks. We're planning to rewrite the transliteration this summer because the mapping/configuration is hard to maintain, lots of pieces are untested and changes currently require a reindexing of all data. Clearly not the best situation to be in. There are multiple related bugs open https://github.com/twain47/Nominatim/issues?q=is%3Aissue+is%3Aopen+label%3ATransliteration

**Comment by zalexua** [comment] 2017-01-17 19:02
The bug report in Trac says that this issue is fixed.
There one more place where I've reported that this issue is not reproducible anymore, Ukrainian forum - https://forum.openstreetmap.org/viewtopic.php?id=13274

I suppose this issue report might be closed as fixed.

**Comment by lonvia** [comment] 2017-01-17 19:13
Yes, indeed, it's fixed and we had a reimport so there should be no bad indexes anymore on nomiantim.osm.org.

**Closed by lonvia** 2017-01-17 19:13 UTC
Labels: bug, Transliteration
