### ISSUE TITLE
Continuous update fails ...

### ISSUE THREAD

**Issue by spin0us** [twain47/Nominatim#458] opened 2016-06-01 11:11 UTC
I've installed a new server using [wiki installation guide](http://wiki.openstreetmap.org/wiki/Nominatim/Installation)
Installation ... OK
Full planet import ... OK
Then i start the update process using the : `./utils/update.php --import-osmosis-all --no-npi`
No problem during many days, but today i see this error : 
```
/usr/bin/osmosis --read-replication-interval workingDirectory=/home/Nominatim/settings --simplify-change --write-xml-change /home/Nominatim/data/osmosischange.osc
01-Jun-2016 13:01:34 org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.40.1
01-Jun-2016 13:01:34 org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
01-Jun-2016 13:01:34 org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
01-Jun-2016 13:01:34 org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
01-Jun-2016 13:01:39 org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Pipeline entities are not sorted, previous entity type=Node, id=125400, version=6 current entity type=Node, id=125400, version=6.
        at org.openstreetmap.osmosis.core.sort.v0_6.SortedHistoryChangePipeValidator.process(SortedHistoryChangePipeValidator.java:50)
        at org.openstreetmap.osmosis.set.v0_6.ChangeSimplifier.process(ChangeSimplifier.java:39)
        at org.openstreetmap.osmosis.core.sort.v0_6.ChangeSorter.complete(ChangeSorter.java:64)
        at org.openstreetmap.osmosis.replication.v0_6.ReplicationDownloader.processComplete(ReplicationDownloader.java:93)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:288)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:349)
        at java.lang.Thread.run(Thread.java:701)
01-Jun-2016 13:01:39 org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
Error: 1
```

**Comment by lonvia** [comment] 2016-06-01 12:02
Please provide your current settings/state.txt and settings/configuration.txt (will be in the build directory if you run the github master version).

**Comment by lonvia** [comment] 2016-06-01 12:22
Never mind, found it. The replication files on planet.osm.org are broken (again). As a quick fix you can try to switch to hourly or daily change files, they look ok.

**Comment by mtmail** [comment] 2016-06-01 12:26
I can confirm the daily change file for June/1st worked fine this night.

**Comment by lonvia** [comment] 2016-06-01 12:33
Another way to work around the problem: reduce maxInterval in settings/configuration.txt to 20, run updates to catch up another 3-4 hours, then switch maxInterval back to your value of choice.

**Comment by spin0us** [comment] 2016-06-01 13:02
Thx for your help.

**Comment by spin0us** [comment] 2016-06-02 06:18
I think i close to quickly ... I've reduced maxInterval in settings/configuration.txt to 20 and the process restart well. But after some completion, it seems to stall again but without error.
```
XXXXX:/home/Nominatim# ./utils/update.php --import-osmosis-all --no-npi
/usr/bin/osmosis --read-replication-interval workingDirectory=/home/Nominatim/settings --simplify-change --write-xml-change /home/Nominatim/data/osmosischange.osc
02-Jun-2016 08:16:16 org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.40.1
02-Jun-2016 08:16:17 org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
02-Jun-2016 08:16:17 org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
02-Jun-2016 08:16:17 org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
```
Is there any way to see want happen ?

**Comment by lonvia** [comment] 2016-06-02 07:18
The data on planet.osm.org has been fixed in the meantime. Might be possible that osmosis still cannot handle it. Can you post your current configuration.txt and state.txt after all?

**Comment by spin0us** [comment] 2016-06-02 08:18
```
XXXXX:/home/Nominatim# cat settings/configuration.txt
# The URL of the directory containing change files.
baseUrl=http://planet.openstreetmap.org/replication/minute

# Defines the maximum time interval in seconds to download in a single invocation.
# Setting to 0 disables this feature.
maxInterval = 3600
XXXXX:/home/Nominatim# cat settings/state.txt
#Wed Jun 01 15:48:58 CEST 2016
sequenceNumber=1913619
timestamp=2016-05-09T19\:22\:02Z
```

**Comment by spin0us** [comment] 2016-06-03 05:52
Is there any debug option for command line to display more information ?

**Comment by lonvia** [comment] 2016-06-03 12:14
There was still a problem with the server. planet.osm.org should be really fixed now.

You can debug this kind of stuff by running the osmosis command as printed by hand and adding '-v 10'.

**Closed by lonvia** 2016-06-03 12:14 UTC

**Comment by Rajavelu** [comment] 2018-05-28 08:09
hi
I met the same problem now. (Working fine till 2 weeks before).
Kindly help someone to me to solve this issue.

**State.txt**
#Wed May 09 00:01:16 PDT 2018
sequenceNumber=49457
timestamp=2018-05-05T00\:00\:00Z

**local.php**
<?php
@define('CONST_Postgresql_Version', '9.4');
@define('CONST_Postgis_Version', '2.1');
@define('CONST_Path_Postgresql_Contrib', '/home/sas/postgres/share/contrib/');
@define('CONST_Website_BaseURL', 'http://localhost:8080/maps/');
@define('CONST_Osmosis_Binary', '/home/sas/Nominatim/osmosis/bin/osmosis');
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day');
@define('CONST_Replication_MaxInterval', '3600');     
@define('CONST_Replication_Update_Interval', '86400');  

**configuration.txt** 
baseUrl=http://planet.openstreetmap.org/replication/day
maxInterval = 86400

I have tried https://planet.openstreetmap.org/replication/hour instead of https://planet.openstreetmap.org/replication/day  but still met same error.

**Comment by mtmail** [comment] 2018-05-28 08:15
@Rajavelu Please open a new github issue. This one is 2 years old.

**Comment by Rajavelu** [comment] 2018-05-28 08:16
@mtmail ok

**Comment by mtmail** [comment] 2018-05-28 08:38
@Rajavelu On May/9th https://planet.openstreetmap.org/ started redirecting all http requests to https (https://git.openstreetmap.org/chef.git/commitdiff/5924746). Try using https in your `settings/configuration.txt`

**Comment by Rajavelu** [comment] 2018-05-28 10:03
@mtmail Thanks for your reply. But still not working. Met connection timeout err. :(

org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
May 28, 2018 2:53:13 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read the state from the server.
    at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:116)
    at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:50)
    at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:290)
    at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:383)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

**Comment by mtmail** [comment] 2018-05-28 10:04
@Rajavelu Please open a new github issue. This one is 2 years old.
