### ISSUE TITLE
Suggestion: combine search results

### ISSUE THREAD

**Issue by freemeng** [twain47/Nominatim#332] opened 2015-11-14 02:21 UTC
As we all know,the road is often divided into many segments for bridge/tunnel/changing of road's property.When we search a road on nominatim,nominatim will return many results,actually,they are the same road.For example:http://nominatim.openstreetmap.org/search.php?q=%E5%BB%BA%E8%AE%BE%E8%B7%AF&viewbox=114.01%2C36.75%2C119.95%2C33.73&polygon=1. As Nominatim  returns too many reslults,it is difficult to find the result we need.
I suggest that nominatim  combine search results.The rule is when two roads crosses and have the same name,they are the same road.
If it's difficult to do,help to tell OSM as a programmer.Maybe mappers should use relation to name the road.

**Comment by lonvia** [comment] 2016-01-31 08:24
See also https://trac.openstreetmap.org/ticket/4952

**Comment by lonvia** [comment] 2016-04-24 20:57
Actually a duplicate of #114.

**Closed by lonvia** 2016-04-24 20:57 UTC
Labels: duplicate, enhancement, Search
