### ISSUE TITLE
UK post code correction: M21 9WP and M21 9PW

### ISSUE THREAD

**Issue by crantok** [twain47/Nominatim#431] opened 2016-04-20 13:25 UTC
Is this the correct place to submit this kind of errata?...

Searching Nominatin for `M21 9WP` returns no exact results.

- In reality, [Longford Road](http://nominatim.openstreetmap.org/details.php?place_id=49908361) contains all houses with the M21 9WP postcode.
- Longford Road also contains at least one other postcode.
- The details page for Longford Road specifies a place:postcode of M21 9PW. This is incorrect.

Many results were returned that contained a postcode of `M21 9PW`.

* All the addresses I am aware of with a postcode of M21 9PW are on [Manchester Road](http://nominatim.openstreetmap.org/details.php?place_id=50530929) so the place:postcode of M21 9PW is correct there. Any other nodes that show a place:postcode of M21 9PW are suspect.
* The name on that detail page is given as Manchester Road East. That is incorrect. The name is just Manchester Road.

**Comment by lonvia** [comment] 2016-04-24 20:38
This kind of error is really a data problem, so rather out-of-scope for this bug tracker.

The problem is that OpenStreetMap doesn't really have house number data with postcodes around Longford Road. So it makes a guess and uses the closest postcode it can find in the data, from a [bakery near Claridge Road](http://www.openstreetmap.org/node/738211417). This can be fairly easily fixed by adding the houses with their numbers in Longford Road. The street name for Manchester Road can be fixed directly in OSM as well.

**Closed by lonvia** 2016-04-24 20:38 UTC
Labels: invalid

**Comment by crantok** [comment] 2016-04-25 10:14
Thanks for the pointers on how to address these issues. I'll follow those up.
