### ISSUE TITLE
place node is loaded but isn't in search result?

### ISSUE THREAD

**Issue by it4workflow** [twain47/Nominatim#433] opened 2016-04-21 18:44 UTC
The following place is loaded in nominatim: 
http://nominatim.openstreetmap.org/details?osmtype=N&osmid=289812744

But if you search for "Steckenborn" the place-Node isn't in the result list, why?

**Comment by mtmail** [comment] 2016-04-21 21:17
It works in my local installation.

@lonvia The detail page shows
```
var nominatim_result = {
    "outlinestring": "POINT(6.3509489 50.6276228)",
    "lon": null,
    "lat": null
};
```
so it could be the `geometry` column is fine, but the centre point didn't get parsed correctly. I've never seen this before. The node is over a year old.

**Comment by lonvia** [comment] 2016-04-21 21:29
The missing centroid is known, see also 52265a33ba2fa4e6f862688909f43fab1c13817d. Not sure it is related to the node being dropped.

**Comment by lonvia** [comment] 2016-04-21 21:39
It wasn't properly indexed. Not sure what the issue is. It might have been originally linked to an administrative boundary and updates didn't clean that up correctly.

**Comment by lonvia** [comment] 2016-04-21 21:44
The changeset at fault is: http://www.openstreetmap.org/changeset/38207753. By removing the name tag from the relation, Nominatim is no longer able to match name and relation. So the link between the two was removed but the place node was not reindexed.

**Comment by it4workflow** [comment] 2016-04-22 03:26
Hi lonvia, please also have a look to http://forum.openstreetmap.org/viewtopic.php?id=54376. Thanks

**Comment by lonvia** [comment] 2016-04-24 20:47
Actually a duplicate of #170.

**Closed by lonvia** 2016-04-24 20:47 UTC
Labels: bug, Indexing
