### ISSUE TITLE
About search results

### ISSUE THREAD

**Issue by jandersonmartins** [twain47/Nominatim#582] opened 2016-11-22 20:27 UTC
Hi, I search by place where the blue point is, but this do not have a name... then
the search returns the value where the red point is. Ex: In json {"road":"Rua Cláudia Gomes Cavalcante"} referent to the red point.

How I know that a place do not have a information, like the blue point??

![image](https://cloud.githubusercontent.com/assets/6090691/20540489/87924216-b0e0-11e6-8f0a-7200c01ea3c9.png)

PS: Sorry my bad english, I am learning! 

Thank!

**Comment by lonvia** [comment] 2017-01-15 21:40
Reverse search always returns the closest _named_ object. You can't get the unnamed road object at the moment.

Duplicate of #79. Closing here.

**Closed by lonvia** 2017-01-15 21:40 UTC
Labels: duplicate
