### ISSUE TITLE
Bounding box issues - america

### ISSUE THREAD

**Issue by amnesia7** [twain47/Nominatim#234] opened 2015-02-08 16:25 UTC
There doesn't appear to be a bounding box set for North America: 
http://www.openstreetmap.org/node/36966063
and the bounding box for USA seems to span the entire globe:
http://www.openstreetmap.org/relation/148838

Is the USA bounding box caused by the Alaska issue (https://github.com/twain47/Nominatim/issues/184) if it goes past 180deg?
Is there a workaround for this or should it use a negative value or something so that when the user searches for USA it shows just the USA across the western date line?

Is the bounding box data maintained by Nominatim because when I mentioned the data issue on OSM I was informed it wasn't something OSM contributors would resolve?

**Comment by lonvia** [comment] 2015-02-08 19:06
Nodes never have a (accurate) bounding box. Nominatim simply doesn't have enough information here. For relations it's computed directly from the OSM data as the bounding box around the ways in the relation. The US is indeed hit by #184. The main issue is that it is not quite clear to me what the correct bounding box to return was. Or rather, if the correct solution, which would be something like 175 to -65 wouldn't break a lot of software out there, which assumes that the first coordinate is smaller than the second.

In any case, clearly a duplicate of #184, so closing here.

**Closed by lonvia** 2015-02-08 19:06 UTC
