### ISSUE TITLE
Address interpolation confused by intermediate address nodes

### ISSUE THREAD

**Issue by vadmium** [twain47/Nominatim#253] opened 2015-03-05 23:53 UTC
It seems that address interpolation is not working well when there is a single “way” with internal address nodes. For instance, at the moment there is a way tagged _addr:interpolation=odd_ that connects three Sydney Rd address nodes: 233–313–551. For reference, the intermediate address node is <https://www.openstreetmap.org/node/3385232218> (313 Sydney Rd).

When searching for say 235 Sydney Rd, no address result is given. When searching for 315 Sydney Rd, a search result is given, but it appears next to 233, and on the wrong side of 313. It is as if only the last two nodes in the way (313 and 551) are considered, but those nodes are assumed to be the endpoints.

A workaround seems to be to split the interpolation up so that it only has a start and end address, with no intermediate addresses (or nodes?). I will shortly try this on the interpolation described above, making separate interpolations for 233–313 and 313–551.

**Comment by lonvia** [comment] 2015-03-06 07:12
I see that you have already split the way. That's unfortunate because now it is impossible to check in the database what exactly went wrong.

Closing this issue because it is not reproducible. If you find another example of this problem, please reopen this bug report and leave the faulty data.

**Comment by vadmium** [comment] 2015-03-06 09:20
Thanks for looking at this and I’m sorry for removing the data. Here’s an example on the other side of that street which I will leave alone:

<https://www.openstreetmap.org/way/98106819>

This way has _addr:interpolation=even_ and has seven address nodes: 578–594–602–608–614–630–676. A search for number 580 (should be close to the start) does not return any specific addresses, just roads: <https://www.openstreetmap.org/search?query=580+Sydney+Rd+3056>. A search for number 632 (should be next to the Brunswick police station) gives a result, but it is at the wrong position, next to number 578: <https://www.openstreetmap.org/search?query=632+Sydney+Rd+3056>.

**Comment by lonvia** [comment] 2015-03-06 09:38
Thanks. Looks like an error with the geometry, I'll have to have a closer look later.

**Closed** 2015-03-08 17:32 UTC

**Comment by lonvia** [comment] 2015-03-08 18:25
Turned out to be a unlucky combination of two rounding problems. First osm2pgsql has a rounding problem during import which causes the point geometry of the address points to be slightly off the wt of the address interpolation. Then, ST_ClosestPoint was slightly off when computing the point on the interpolation, which eventually tripped ST_Split, when splitting the interpolation into parts.

The fix is now deployed on osm.org and I have kicked your example way. The addresses there are now correct. Other interpolations will fix themselves gradually, whenever they get updated.
