### ISSUE TITLE
Typos in Norway

### ISSUE THREAD

**Issue by VikRubrikk** [twain47/Nominatim#579] opened 2016-11-16 11:09 UTC
I was looking at the breakdown of Norway into regions in https://osm.wno-edv-service.de/boundaries/

(We need such regions for a project, we were hoping to be able to use open source data.)

I noticed several issues with the Norwegian breakdown. Most counties use Norwegian names, but not all.
* Finnmark is using a presumably Sami name
* Vest-Agder, Sogn og Fjordane, Bouvetøya are using English default names. (It may be that my settings choose English when there is a choice, but I have never heard Vest-Agder translated before, and it is weird to translate "West", but not "East".)
* Ytrebygda in Bergen is misspelled as Ytrebyda

**Comment by lonvia** [comment] 2016-11-16 23:05
This is a data issue not particularly related to search. Please review and edit the underlying OpenStreetmap data. In particular spelling mistakes should be fixed directly in OSM. 

That said, for the English names: the issue is here that although the local names are in the name tag, Nominatim cannot really determine which language they are in because Norway has multiple official languages. So, when you search and give a language preference list of 'Norwegian, English', it will always fall back to the existing name:en tag. The best way to improve the situation is to add name:nb etc. where there are translated names. I suggest to contact the Norwegian OSM community, for example via [their mailing list](https://lists.nuug.no/mailman/listinfo/kart) and discuss how to best resolve that countrywide.

**Closed by lonvia** 2016-11-16 23:05 UTC
