### ISSUE TITLE
How to get the bounding box and outline of an element on specific coordinates

### ISSUE THREAD

**Issue by SoonDead** [twain47/Nominatim#376] opened 2016-02-25 15:18 UTC
If I do a regular search I can just add `polygon_geojson=1` to the query, I get the outline of each result and I can also get the bounding box for a result.

If I select a coordinate I can reverse geocode it to get the address at that location. I get the `osm_id` of that specific object, but I could find no way to get the outline or bounding box of that osm object. How come?

I could take the result of the reverse geocode, make that address to a string and try the regular search with it hoping to find the same osm_id and osm_type between the results. But how dodgy is this?

Surely there must be a better way.

Edit: searching by the display name does not work in every case. I'm trying to get the bounding box of the object in the following coordinates: `{ lat: 51.48722, lon: -0.124444 }`. This results in the MI6 building in london:

Request:

http://nominatim.openstreetmap.org/reverse?addressdetails=1&format=json&lat=51.48722&lon=-0.124444&accepted-language=en

Response:

    {"place_id":"65523547","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"32998733","lat":"51.4872959","lon":"-0.12437490349424","display_name":"Secret Intelligence Service, 85, Albert Embankment, Vauxhall, London Borough of Lambeth, London, Greater London, England, SE1 7TP, United Kingdom","address":{"building":"Secret Intelligence Service","house_number":"85","road":"Albert Embankment","suburb":"Vauxhall","city":"London","state_district":"Greater London","state":"England","postcode":"SE1 7TP","country":"United Kingdom","country_code":"gb"}}

Now If I search for that display name to find the bounding polygon:

Request:

http://nominatim.openstreetmap.org/search.php?format=json&polygon=1&addressdetails=1&q=Secret%20Intelligence%20Service%2C%2085%2C%20Albert%20Embankment%2C%20Vauxhall%2C%20London%20Borough%20of%20Lambeth%2C%20London%2C%20Greater%20London%2C%20England%2C%20SE1%207TP%2C%20United%20Kingdom&accept-language=%20en

Response:

    []

I can manually simplify the url like: http://nominatim.openstreetmap.org/search.php?format=json&polygon=1&addressdetails=1&q=Secret%20Intelligence%20Service&accept-language=%20en and it will yield the result I want. But I need to do this programmatically.

**Comment by lonvia** [comment] 2016-02-25 16:07
Duplicate of #138 and #150.

**Closed by lonvia** 2016-02-25 16:07 UTC
Labels: duplicate
